all: mfqs/mainmfqs.cc rts/mainrts.cc whs/mainwhs.cc main.cc
	g++ ./mfqs/mainmfqs.cc -o ./mfqs/mfqs
	g++ ./rts/mainrts.cc -o ./rts/rts
	g++ ./whs/mainwhs.cc -o ./whs/whs
	g++ ./main.cc -o ./main
clean:
	rm mfqs/mfqs rts/rts whs/whs main
	
